language: node_js
node_js:
  - "7.0.0"
env:
  - CXX=g++-4.8
before_script:
  - "mkdir -p ./.config && cp ./.ci-files/config.yml ./.config"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
