language: node_js
node_js:
  - "7.0.0"
before_script:
  - "npm run dtsm"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
    - $HOME/.dtsm
