maintainer: syuilo <i@syuilo.com>
url: 'http://misskey.local'
port: 80
https:
  enable: false
  key: null
  cert: null
recaptcha:
  siteKey: 6LdtwxUTAAAAAJlGBV9_fxy-szKJ-3hCscF3md76
  secretKey: 6LdtwxUTAAAAAHOcFtsjHZn0Cj-OILDyB1xA9rWc
core:
  apikey: 'Himasaku#06160907'
  url: 'http://api.misskey.local:616'
proxy:
  url: 'http://localhost:8003'
